--- 
- name: Another way to create multiple files using loop
  hosts: all 
  become: true
  vars:
    reqFiles:
      config:
        mode: "0660"
        dir: "/opt"
      config.default:
        mode: "0660"
        dir: "/home/pt"
        owner: "pt"
        group: "root"
      config.test:
        mode: "0750"
        dir: "/tmp"
  tasks:
    - name: Simple message to see which files are created in which directory
      ansible.builtin.debug:
        msg: "The files {{ item.key }} will be created in {{ item.value.dir }} location"
      with_dict: "{{ reqFiles }}"
    - name: Create the files on the target directory
      ansible.builtin.file:
        path: "{{ item.value.dir }}/{{ item.key }}"
        state: touch
        mode: "{{ item.value.mode }}"
        owner: "{{ reqFiles['config.default'].owner }}"
        group: "{{ reqFiles['config.default'].group }}"
      with_dict: "{{ reqFiles }}"
      #when: item.key != "config.default"
#The dict was created with the msg below

# ok: [192.168.56.9] => (item={'key': 'config', 'value': {'mode': '0660', 'dir': '/opt'}}) => {
#     "msg": "The files config will be created in /opt location"
# }
# ok: [192.168.56.9] => (item={'key': 'config.default', 'value': {'mode': '0660', 'dir': '/home/pt', 'owner': 'pt', 'group': 'root'}}) => {
#     "msg": "The files config.default will be created in /home/pt location"
# }
# ok: [192.168.56.9] => (item={'key': 'config.test', 'value': {'mode': '0750', 'dir': '/tmp'}}) => {
#     "msg": "The files config.test will be created in /tmp location"
#}

...
      