--- 
- name: Another way to create multiple files using loop
  hosts: all 
  become: true
  vars:
    reqFiles:
      config:
        mode: "0660"
        dir: "/opt"
      config.default:
        mode: "0660"
        dir: "/home/pt"
        owner: "pt"
        group: "root"
      config.test:
        mode: "0750"
        dir: "/tmp"
  tasks:
    - name: Simple message to see which files are created in which directory
      ansible.builtin.debug:
        msg: "The files {{ item.key }} will be created in {{ item.value.dir }} location"
      with_dict: "{{ reqFiles }}"
    - name: Create the files on the target directory
      ansible.builtin.file:
        path: "{{ item.value.dir }}/{{ item.key }}"
        state: absent
        mode: "{{ item.value.mode }}"
        owner: "{{ reqFiles['config.default'].owner }}"
        group: "{{ reqFiles['config.default'].group }}"
      with_dict: "{{ reqFiles }}"
      #when: item.key != "config.default"
...
      