#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-httpd
  - name: Install web app package on Debian based OS
    ansible.builtin.apt:
      name: "{{ pkg.get(ansible_facts['os_family']) }}"
      state: present
      update_cache: true
    when: ansible_facts['os_family'] == "Debian"
  - name: Install web app package on RHEL based OS 
    ansible.builtin.dnf:
      name: "{{ pkg.get(ansible_facts['os_family']) }}"
      state: present
      update_cache: true
    when: ansible_facts['os_family'] == "RedHat"
  - name: Copy customized index.html to /var/www/html/
    ansible.builtin.template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: Restart web app servers
...
