---
- name: Simple loop example play
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create a number of files in /tmp directory
      ansible.builtin.file:
        path: /tmp/"{{ item }}""
        state: touch
        mode: 0660
      loop:
        - test1
        - test2
        - test3
...