---
- name: Using loop to install multiple packages
  hosts: all
  become: true
  tasks:
  - name: Install the packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - wget
      - curl
      - nginx
...


