---
- name: Create multiple files in different directory
  hosts: all
  become: true
  vars:
    target_file:
      - { name: 'index.html', dir: '/var/www/html/', mode: '0660', owner: 'nginx', group: 'nginx' }
      - { name: 'error.html', dir: '/var/www/html/', mode: '0660' }
      # index.html:
      #   dir: /var/www/html/
      #   mode: 0660
      #   owner: nginx
      #   group: nginx
      # error.html:
      #   dir: /var/www/html/
      #   mode: 0660
  tasks:
    - name: Check with debug message
      ansible.builtin.debug:
        msg: "files={{ item.name }} directory={{ item.dir }}"
...
