---
- name: Install java and set home environment for java
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Downloading the required tar.gz file 
      ansible.builtin.get_url: 
        url: https://download.java.net/java/GA/jdk24/1f9ff9062db4449d8ca828c504ffae90/36/GPL/openjdk-24_linux-x64_bin.tar.gz
        dest: /opt/openjdk-24_linux-x64_bin.tar.gz

    - name: Extracting the tar file
      ansible.builtin.unarchive:
        src: /opt/openjdk-24_linux-x64_bin.tar.gz
        dest: /opt
        remote_src: true

    - name: Set JAVA_HOME ENV variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: export JAVA_HOME=/opt/jdk-24
        state: absent


